// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as customWidgets from './customWidgets';

export const visitedPlacesIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'visitedPlacesIntro',
    containsHtml: true,
    text: (t: TFunction) => t('destinations:visitedPlacesIntro'),
    conditional: defaultConditional
};

export const frequentVisitedPlaces = customWidgets.frequentVisitedPlaces;

export const visitedPlaceName: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'name',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('destinations:name'),
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const visitedPlaceGeography = customWidgets.visitedPlaceGeography;

export const visitedPlaceFrequency: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'frequencyWeekly',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('destinations:frequencyWeekly'),
    valueRange: {
        min: 1,
        max: 7
    },
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const destinations_save: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'destinations.save',
    label: (t: TFunction) => t('destinations:destinations.save')
};
