// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { getAndValidateSurveySections, SurveySectionsConfig } from 'evolution-common/lib/services/questionnaire/types';
import householdConfigs from './sections/household/sectionConfigs';

// Export all the sections configs
const sectionsConfigs: SurveySectionsConfig = {
    household: householdConfigs
};
export default getAndValidateSurveySections(sectionsConfigs);
