// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import * as householdWidgets from './sections/household/widgets';

// Define all the widgets
const widgets: { [key: string]: any } = {};

// Define all the sections widgets
const sectionsWidgets = [householdWidgets];

// Loop all sections and add their widgets to the widgets object
sectionsWidgets.forEach((section) => {
    for (const widget in section) {
        widgets[widget] = section[widget];
    }
});

// Export all the widgets
export { widgets };
