// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';

export const household_size: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.size',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('household:household.size'),
    valueRange: {
        min: 1,
        max: 6
    },
    overMaxAllowed: true,
    conditional: defaultConditional,
    validations: validations.householdSizeValidation
};

export const household_carNumber: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.carNumber',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('household:household.carNumber'),
    valueRange: {
        min: 0,
        max: 5
    },
    overMaxAllowed: true,
    conditional: defaultConditional,
    validations: validations.carNumberValidation
};

export const household_bicycleNumber: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.bicycleNumber',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('household:household.bicycleNumber'),
    valueRange: {
        min: 0,
        max: 5
    },
    overMaxAllowed: true,
    conditional: defaultConditional,
    validations: validations.bicycleNumberValidation
};
